version: "3.5"

services:
  web: 
    image: yuloskov/devops:master
    ports: 
      - 5000:5000
    logging:
      driver: "json-file"
      options: 
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"
        max-size: "1000k"
        max-file: "2"
    volumes:
      - ./data:/data
    environment:
      DATA_PATH: '/data/times.txt'