version: '3.7'


services:
  promtail:
    image: grafana/promtail:${LOKI_VERSION}
    volumes:
      - /var/lib/docker:/var/lib/docker:ro
      - ./promtail/scrape-config.yml:/etc/promtail/config.yml:ro
    command: -config.file=/etc/promtail/config.yml

  loki:
    image: grafana/loki:${LOKI_VERSION}
    ports:
      - 3100:3100
    command: -config.file=/etc/loki/local-config.yaml

  grafana:
    image: grafana/grafana:${GRAFANA_VERSION}
    volumes:
      - grafana-volume:/var/lib/grafana
    ports:
      - 3000:3000

  prometheus:
    image: prom/prometheus:${PROMETHEUS_VERSION}
    volumes:
      - prometheus-volume:/prometheus
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090

volumes:
  grafana-volume:
  prometheus-volume: