- name: Copy file with owner and permissions
  ansible.builtin.copy:
    src: ../../../app_python/docker-compose.yml
    dest: /opt/
    owner: ubuntu
    group: ubuntu
    mode: '0644'

- name: Run container
  become: True
  shell:
    cmd: "docker-compose up -d"
    chdir: /opt/