---
- name: Ensure dependencies are installed.
  apt:
    name:
      - apt-transport-https
      - ca-certificates
    state: present

- name: Add Docker apt key.
  apt_key:
    url: "https://download.docker.com/linux/ubuntu/gpg"
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    state: present
    validate_certs: False
  register: add_repository_key
  ignore_errors: true

- name: Add Docker repository.
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
    state: present
    update_cache: true


- name: Install Docker.
  package:
    name: "docker-ce"
    state: "present"
  ignore_errors: true

- name: Ensure docker users are added to the docker group.
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: true
    
- name: Install Docker Compose.
  get_url:
    url: "https://github.com/docker/compose/releases/download/1.26.0/docker-compose-Linux-x86_64"
    dest: "/usr/local/bin/docker-compose"
    mode: 0755
