name: Python application
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        pip install -r app_python/web/requirements.txt;
        pip install pytest;
        pip install pylint
    - name: Lint
      run: |
        pylint ./app_python

  test:
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        pip install -r app_python/web/requirements.txt;
        pip install pytest
    - name: Test with pytest
      run: |
        pytest -v

  build:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build docker
      run: |
        docker build app_python/web
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
